### ISSUE TITLE
traefik local setup not working

### ISSUE THREAD

**Issue by mooglestiltzkin** [ianepreston/recipes#30]
read your blog but couldnt get it to work
https://blog.ianpreston.ca/docker/traefik/networking/tip/2021/01/09/traefik-lan.html#setting-up-traefik

in ur guide u mentioned about setting up route for dns in pfsense so that it would get to work. but when i tried doing that, pfsense was not happy :{ so not sure wut i did wrong.

Mostly following this guide but got stuck
https://github.com/Heziode/traefik-v2-https-ssl-localhost

before i found your blog that mentioned those stuff that get left out (people expecting u to know these stuff, but we don't yet. so here i am :{ )

I'm available on discord if ur free to help
https://discord.gg/Zj9EYsf

**Comment by ianepreston** [comment]
Looks like your issue got resolved over here: https://github.com/Heziode/traefik-v2-https-ssl-localhost/issues/5 ok if I close this?

**Comment by mooglestiltzkin** [comment]
yes we managed to resolve it. thx :}
